# -*- coding: utf-8 -*-
a=["'Un trabajo bien hecho'\n[ACTO I]\n\nHan sido meses de duro esfuerzo. Tal vez años, no estás segura. Desde tus humildes inicios como aventurera en el poblado de Släkt has llegado a la cima del mundo, a las propias puertas de Trofast, la guarida del malvado Tjena. El viento gélido te atraviesa como una espada. Estás deseando acabar con todo esto de una maldita vez.",
  ["\n\n1 - Echar abajo la puerta","Echas la puerta abajo de una patada.\n","c1","b"],
  ["\n2 - Pensárselo un poco más","¿Pensar qué? Llevas años intentando llegar donde estás ahora. ¡No es el momento de echarse atrás! ¿Vas a rendirte ahora? ¿De verdad? No, ¿Verdad? Claro que no, quieres ver cómo acaba la aventura.\nTras darle un par de vueltas, decides descartar esa idea y empezar de nuevo.\n","c1","a"]]

b=["Tjena está en su trono de hielo. Tan seguro está de su poder que apenas se da cuenta cuando entras. Te mira mientras te aproximas a él, lenta pero deliberadamente, sin inmutarse. Tardas lo que te parece una eternidad en llegar a la plataforma donde está sentado. Más cerca que nunca. Casi al alcance de tu espada. Casi... Tjena no se inmuta, mirando en tu dirección con una expresión aburrida.",
  ["\n\n1 - ¡Tjena! ¡Ha llegado tu hora!","Con la mano en tu espada, alzas la voz tanto como te sea posible. Tu único miedo es que tus palabras se desvanezcan en la vasta estancia.\n","c1","c"], 
  ["\n2 - ¡Atacar! ¡Atacar sin piedad!","No has llegado hasta donde estás a base de dudas. Sin pensártelo dos veces, desenvainas tu espada y te lanzas hacia él.\n","c1","d"]]

c=["Tjena te mira sin cambiar de expresión. Tal vez tus palabras se han quedado un poco cortas. No estás segura de si ha entendido lo cerca que está su final. El silencio es realmente incómodo.",
  ["\n\n1 - Insistir","- '¡Eh!'. Intentas insistir, subiendo un poco más la voz. \n","c1","e"],
  ["\n2 - ¡Atacar ahora que no se lo espera!","You get closer to the door\n","c1","d"]]

d=["Te lanzas sobre Tjena, levantando tu espada con un movimiento perfectamente estudiado. Tus reflejos bien entrenados son lo único que te impide distinguir el momento en el que su indiferencia se transforma en sorpresa, y su sorpresa en resolución ante el inminente combate. Tu espada pasa a unos centímetros de su cuerpo con un silbido, y lo próximo que ves es su imponente figura, plantada frente a ti, listo para todo.",
["\n\n1 - Continuar con tu ataque","La suerte está echada. Sólo hay una salida. Decides continuar con tu ataque\n","c1","g"],
["\n2 - Dar un paso atrás","Decides dar un paso atrás para reevaluar la situación\n","c1","l"],
["\n3 - Dialogar\n","Se te ocurre que a lo mejor haya otra solución. Das un paso hacia atrás y bajas tu espada.\n","c1","l"]]

e=["Tjena está mirando en tu dirección, pero parece ignorar tu presencia. Tras agitar un poco los brazos consigues que reaccione. Tjena se quita los auriculares y te mira con un aspecto algo confundido. \n- ¿Quién eres, y qué haces aquí?",
["\n\n1 - ¡Soy Gunrid, hija de Nävlinge, hija de Bekant! He venido a restaurar el orden en el reino. He venido a acabar contigo. ¡En guardia Tjena! ¡Enfréntate a tu final!","Tal vez el diálogo haya salido un poco exagerado. Tienes que reconocer que sonaba mejor en tu cabeza. Pero lo dicho está dicho, y sólo queda ver si Tjena se lo va a tomar en serio o no Esperas que sí, si no menudo palo.","c1","f"],
["\n2 - [Atacar]","Ya lo has intentado antes, y estás cansada de las palabras. No tienes nada más que decir. Sin pensártelo dos veces desenvainas tu espada y te abalanzas sobre él.\n","c1","d"]]

f=["- 'Vaya, otro aventurero perdido'.\n- 'Aventurera', le corriges.\n- 'Perdona. Es la armadura supongo. Otra aventurera perdida. Tampoco es que haya mucha diferencia entre un cadáver y el siguiente.' \n- 'No estoy perdida', insistes. 'Estoy exactamente donde necesito estar'.\n- 'Deja que lo adivine. Has venido a la guarida del malvado usurpador del trono' \n- 'Sí, exacto' \n- 'Y vas a intentar acabar conmigo' \n- 'He sido muy clara en ese sentido, sí' \n- 'Y cuando lo consigas todos los problemas del reino desaparecerán de la noche a la mañana. Así, como por arte de magia' \n- '¡Sí, claro! ¡Has corrompido el reino con tu magia oscura, cuando acabe contigo se levantará el velo siniestro que oscurece nuestro futuro y podremos ver salir el sol de nuevo, con esperanza en el futuro!', dices hinchando el pecho, satisfecha con tu discurso. Los puntos en persuasión han merecido la pena. \n- '¿El sol? ¿Os habéis quedado sin sol? No sé de qué me hablas, pero eso no es cosa mía. El puesto de emperador de hielo tenebroso es meramente administrativo.' \n- 'Era una metáfora...' \n- 'Ah.'",
["\n\n1 - 'Mira, no me estás entendiendo, o te largas o te largo. Llevo meses cargándome a tus minions, ¿Quieres que sigamos por las malas?.'\n","Tjena se apoya en su trono, sorprendido por tu franqueza. Notas algo se nu mirada.\n","c1","i"],
["\n2 - 'Si es que además de maligno resulta que eres bobo. Normal que el IPC esté por las nubes.'","Tjena te mira con el ceño fruncido. No parece agradado por tu comentario. Imaginas que era la idea.\n","end","b"],
["\n3 - 'Pero qué mal me caes joder. Ven aquí que te corto en dos'\n", "Sin más palabras, desenvainas tu espada y te acercas hacia él, confiada en tu poder\n.", "c1","d"]]

g=["Continúas tu ataque sin piedad y sin pausa. A pesar de todo lo que has aprendido, Tjena tiene el poder del mal de su lado. Rozarle con tu espada sólo consigue dejar muescas en la superficie, sin que su túnica llegue siquiera a rasgarse. Tras un intercambio de varios minutos, ves cómo Tjena levanta la mano, señalando a tu espada. Lo próximo que sientes es el metal explotando en mil pedazos, desintegrándose entre tus dedos, hasta que la herramienta de la que ha dependido tu vida desde que comenzaste tu aventura no es más que una mancha sobre el hielo.\n- '¿Y ahora qué, aventurera?', dice con un claro tono sarcástico.",
["\n\n1 - Activar Vonsbäk, el anillo del poder","Aún tienes un as bajo la manga. O mejor dicho, en tu dedo. El anillo del poder, pescado directamente de las profundidades del volcán Lerhyttan. Intentas no pensar en lo difícil que fue encontrar el material necesario para reconstruir a Duktig, la legendaria caña de pescar. Cierras tu puño con fuerza, concentrándote en el anillo. Notando su poder, y el calor emanando de su superficie.\n\nPara cuando Tjena se da cuenta de lo que vas a hacer, es demasiado tarde. Tu puño avanza implacable, y un instante después impacta directamente en su pecho. Ves cómo tu enemigo da un paso hacia atrás, sorprendido. \n\n-'¿Qué ha sido eso?\n- '¡Tu final! ¡Siente el poder de Vonsbäk, el anillo del poder!'\n- 'Vons... ¿Qué?'\n- '¿El anillo del poder? ¿Del volcán Lerhy... Lerhu...'\n- 'Ah, ¿Lerhyttan?'' \n- Sí, eso\n- '¿Conseguiste reconstruir a Duktig?\n- '¡Así es!'\n- 'Admiro tu coraje. Tu paciencia, más bien. Pero no creo que eso vaya a funcionar.'\n- 'El propio Påtår me dijo que caerías ante su poder!'\n- 'Léete la letra pequeña. Te dejo un minuto si lo necesitas'\n\nLees la descripción del artefacto y susurras una maldición. ¿Tal vez deberías haberlo hecho antes? Menudo corte. Sacas tu espada de repuesto y vuelves a la carga.\n","c1","g"],
["\n2 - Invocar a Bjärnum, diosa de Grönlid","Reconoces la situación como lo que es: Un momento desesperado, el límite de lo que puedes hacer como un humano ante la encarnación del mal. No hay artefacto o magia que puedas utilizar ante semejante enemigo. Sólo hay alguien que pueda. \nTras dar un paso hacia atrás, cierras los ojos y llamas a Bjärnum desde el fondo de tu corazón.\n","c1","h"],
["\n3 - Utilizar Eneryda, el poder prohibido de Skarsta","Las espadas no funcionan. Tal vez era de esperar. Lo que necesitas es magia. Magia destructiva. Lo más destructiva posible. Tan destructiva que está prohibida. El propio Alefjäll te hizo prometer que no lo usarías jamás, pero dadas las circumstancias, crees que su uso está más que justificado. \n\nJuntas tus manos, enfocando tu energía en ellas. El resplandor os ciega a ambos. No te importa. No necesitas ver. Puedes sentir el mal frente a ti, puedes notar la energía derritiendo el lejano hielo en las paredes de la caverna, puedes notar el ansia del universo por desatar su entropía sobre toda existencia conentrarse bajo tu mando. No es momento de dudar. En un instante lanzas tu ataque, y lo último que sientes es el mundo, tus manos, tus brazos, tu cuerpo y todo lo que le rodea desmigándose y desapareciendo frente a tu mirada.","end","a"]]

h=["El delicado y atronador sonido de un coro celestial invade y retruena en la cueva. Ves a Tjena mirar confundido hacia una esquina de la cueva. Uno de los sirvientes esta acompañando al coro de ángeles con un organillo. Frente a ti se materializa la mismísima diosa de Grönild. Te mira sonriente y te hace un leve gesto con la cabeza. En un momento se da la vuelta y señala a Tjena, que desaparece temporalmente en un estallido de luz. Para cuando tu visión se recupera de la luz, la cueva vuelve a estar a oscuras. Tjena permanece inmóvil en su sitio. El sirviente os mira expectante.",
["\n\n1 - ¿Ahora qué?","Los dos os miráis, confundidos. No estás segura de qué ha venido a hacer Bjärnum exactamente.","c1","j"]]

i=["Tjena te mira, exhalando un suspiro.\n\n- 'Pues mira, si te vas a poner así seguimos por las malas'",
  ["\n\n1 - Continuar con el combate","Está claro que ya no hay salida posible. Tras un breve respiro, vuelves a la carga.\n","c1","d"]]

j=["Tjena se yergue en su lugar y te mira de manera desafiante. \n\n- '¡Ha! ¡Estúpido mortal, parece que me has sobreestimado!",
  ["\n\n1 - Espera, ¿Qué?","Le miras extrañado. Tjena cae fulminado al suelo.\n","c1","k"]]

k=["El sirviente continua observando la escena, incrédulo. Le asientes con la cabeza y sales andando de la cueva mientras toca una marcha triunfal en su organillo. Tu misión ha terminado. Eres libre. El reino es libre.",
  ["\n\n1 - Salir de la cueva","","c2","a"]]

l=["Sinceramente, la situación no ha mejorado.",
  ["\n\n1 - Continuar con el combate","","c1","d"]]

  