# -*- coding: utf-8 -*-
a=["'Un trabajo bien hecho'\n[ACTO II]\n\nSales de la cueva, magullada pero con la cabeza alta. El viento sigue estando frío de narices, pero ha dejado de importarte. Desde tu ubicación ves gran parte del reino, desde la costa de Tämnaren hasta el cañón de Lundskär. Casi puedes ver tu hogar desde aquí. Ya estás imaginando tu regreso triunfal, y tu vuelta a una vida tranquila sin más aventuras.\n\nHaces un esfuerzo por no adelantarte a los eventos. Primero debes restaurar los poderes que has ido recogiendo por el camino para derrotar a Tjena. El anillo de poder debe volver a Lerhyttan, la bendición de Bjärnum debe de ser devuelta en el altar de Grönlid y tus habilidades de Eneryda deben de ser olvidadas en el mismo lugar en el que las aprendiste: Las profundidades de Skarsta.\n\nContemplas el horizonte durante unos minutos, mientras piensas en tu próximo paso.",
["\n\n1 - Devolver el anillo a Lerhyttan","Decides volver a Lerhyttan para deshacerte del anillo. Tras saborear tu victoria durante unos minutos, te alejas de la escena de la batalla en dirección a la imponente masa de tierra en el horizonte.","c2","b"],
["\n2 - Viajar al altar de Grönlid","La bendición de bjärnum debe de ser devuelta. Decides viajar al altar de Grönlid\n","c2","c"],
["\n3 - Tratar de olvidar tu poder en Skarsta","Tu mayor temor, una vez derrotado Tjena, es Eneryda, el poder prohibido de Skartsa. Es un último recurso que finalmente no necesitaste y del que estás deseando deshacerte. Las descripciones que tus maestros utilizaron para explicarte cómo funcionaba siguen poniéndote los pelos de punta.\n","c2","d"],
["\n4 - Dejarse de historias y volver a casa","","c3","b"]]

b=["Tus capacidades de orientación nunca fueron las mejores, y agradeces para ti misma la permanente columna de humo sobre la inmensa montaña ardiente.\n\nTe relajas un poco, sabiendo que lo más difícil ya ha pasado y que todo va a ser cuesta abajo a partir de ahora. Es cierto que tuviste que exterminar a cientos de minions genéricos para recuperar el anillo. ¿Quién te va a poner pegas para devolverlo a su sitio?\n\nEn el mismo momento en el que te estás planteando ese escenario, una flecha pasa silbando a tu lado, casi rasgándote la capa. Te han disparado tantas veces que no tardas en saber de dónde ha venido el proyectil. Una figura encapuchada con unos colores extremadamente familiares está al otro lado del arco. Es uno de los minions de Tjena",
["\n\n1 - ¡Al ataque!","Sin pensártelo dos veces cargas contra la figura, espada en mano.\n","c2","e"],
["\n2 - '¡Eh! ¡Que Tjena está muerto! ¡Dejadme en paz ya!","Los constantes ataques de los minions de Tjena han sido una molestia menor hasta ahora. Si acaso, una buena oportunidad para no perder tus habilidades. Pero la situación te parece absurda. Ya has pasado por todo eso, ya has eliminado a Tjena, ya has completado tu misión. Sólo te queda dejar las cosas recogidas. ¿Qué narices les pasa?\n","c2","f"],
["\n3 - Salir pitando\n","No tienes tiempo para estas tonterías. Bueno, en realidad sí que lo tienes, pero andar matando minions cuando ya has despachado al Emperador de Hielo es un poco absurdo. Sabiendo que suelen tardar bastante en lanzar el segundo proyectil, aprovechas para escabullirte en el bosque y continuar tu camino.","c2","h"]]

c=["El templo de Vikfjärd, el hogar de Grönlid, sigue tan en ruinas como la última vez que te adentraste en él. Al menos los pasillos están bien iluminados y libres de animales y amenazas. no ha pasado tanto tiempo desde que tuviste que recorrer el dichoso laberinto para conseguir la bendición de Bjärnum, y no ha habido apenas tiempo para que ninguna molestia nueva se instale en él. Tras volver a trazar tus pasos llegas al altar de Grönlid. Deseando tachar otra cosa de la lista, te pones de rodillas frente al altar y llamas a Bjärnum. Notas la luz y el calor descendiendo sobre ti, y una voz familiar que te llama desde el otro mundo.",
["\n\n1 - ¡Bjärnum! El enemigo ha caído. Vengo a devolver el poder de este templo y a presentarte mis respetos. Sin tu ayuda, el reino estaría perdido.","La vez de Bjärnum es clara como el cristal en tus oídos.\n\n- Gracias, avent... Eh... aventurera. Gracias, aventurera. Todos te debemos el próximo amanecer, desde el animal más minúsculo, hasta el dios más alto del panteón. Tu legendario coraje pasará a los anales de la historia como una inspiración para todos los que vengan. Marcha, heroina, y disfruta del futuro que has labrado para todos'.\n\nNo se te ocurre qué contestar, así que agachas la cabeza en agradecimiento una última vez y sales del templo. Sientes como has dejado el poder de Grönlid atrás, pero eso ya no te preocupa.","c2","k"],
["\n2 - ¿Hola?","Continúas mirando a la pared, esperando un mensaje. No sabes si Bjärnum no te escucha o si te está tomando el pelo.","c2",""],
["\n3 - ¡Epa! Te dejo la bendición debajo del altar, hablamos luego que llego tarde a casa.","Tocas el altar con intención de devolver la bendición. Notas el poder dejando tu cuerpo, y la luz de la estancia desaparece como ha venido. Un poco anticlimático pero oye, no estás para ceremonias ahora mismo.","c2","l"]]

d=["Siguiente tarea, volver a Skarsta y olvidar Eneryda. Es demasiado peligroso como parra virir con ello sin necesidad. No te molestaste en preguntar exactamente cómo funcionaba el proceso, pero estás deseando acabar con ello de una vez. \n\nEl guardián te da la bienvenida, sabiendo que ya habías superado sus retos anteriormente. Las criaturas que habitan en el interior de ese sitio maldito se van escondiendo a tu paso. Parece que las noticias sobre Tjena han viajado rapido, y los rufianes menores temen la mera mención de tu nombre.\n\nNo te cuesta mucho llegar al corazón de la fortaleza. Alefjäll está exactamente donde le dejaste, sentado en su escritorio con una montaña absurda de tomos polvorientos a su alrededor. Te acercas un poco, intentando no molestar. Parece que está dormido.",
["\n\n1 - Darle un susto","","end","e"],
["\n2 - 'Ehem...'","","c2","m"],
["\n3 - ¡Alefjäll! ¡El mal ha sido exterminado! ¡Tjena ya no infecta este mundo con su magia! ¡Libérame de Eneryda, y deshazte de esta carga que ya no tiene razón de ser!","","c2","n"]]

e=["No tardas mucho en llegar a la figura encapuchada. Aún está preparando su arco cuando tu espada desciende sobre ella, hiriéndola gravemente. El minion intanta decirte algo con lo que claramente son sus últimas palabras. Bla bla bla el anillo, bla bla bla evitar que llegues al trono, bla bla bla caña de pescar legendaria. ",
["\n\n1 - Acabar con el minion","Le clavas la espada unas cuantas veces para asegurarte. Tienes que admitir que el diálogo era un poco raro, ¿A lo mejor hubiera tenido más sentido si le hubieras matado antes?\n\nEn cualquier caso, sales intacta de la situación y continúas tu camino.","c2","h"],
["\n2 - Dejarle hablar","","end","c"]]

f=["- '¡No te creo!', te grita desde la distancia. '¡Y no voy a dejar pasar a ningún aventurero sólo porque me diga que mi jefe ha muerto! ¡No tendría ni pies ni cabeza!'\n- '¡Aventurera joder!', gritas por milésima vez.\n- 'Perdón, es la armadura creo. Pero no voy a dejarte pasar de todas formas'\n",
["\n\n1 - Amenazar al minion","","c2","i"],
["\n2 - Darle una oportunidad","","c2","j"],
["\n3 - Dejar que hable","","end","c"]]

g=["Mientras bajas por las escaleras del volcán miras al horizonte, pensando en tu próximo objetivo. Repasas mentalmente la lista de tareas pendientes...",
["\n\n1 - Viajar al altar de Grönlid","La bendición de bjärnum debe de ser devuelta. Decides viajar al altar de Grönlid\n","c2","c"],
["\n2 - Tratar de olvidar tu poder en Skarsta","Tu mayor temor, una vez derrotado Tjena, es Eneryda, el poder prohibido de Skartsa. Es un último recurso que finalmente no necesitaste y del que estás deseando deshacerte. Las descripciones que tus maestros utilizaron para explicarte cómo funcionaba siguen poniéndote los pelos de punta.\n","c2","d"],
["\n3 - No te queda nada por hacer. Volver a casa.","","c3","a"]]

h=["Tras varios días de viaje sin mayores contratiempos, por fin llegas al abrasador Lerhyttan. El penetrante frío de rodeaba el trono helado se torna en un recuerdo agradable mientras subes las escaleras hasta la cima, una a una, mientras te imaginas el cuero de tus suelas estropeándose bajo tus pies por el calor.\n\nEn la cima hay tres figuras esperandote. Una de ellas, Påtår, está pescando en el volcán con la caña que le conseguiste con tanto esfuerzo. Las otras dos son... ¿Más minions de Tjena?\n\nUno de ellos nota tu presencia y ambos se ponen de pie en un instante, bloqueándote el paso.\n\n- '¡Alto ahí aventurero! ¡No podemos dejar que recuperes el Anillo del Poder! Vuelve por donde has venido, ¡O muere!",
["\n\n1 - '¡Aventurera, me cago en tus muelas ya joder!'","Ya no tienes paciencia para estas cosas. Le das una patada al minion con todas tus fuerzas, lanzándolo a la caldera del volcán. La figura encapuchada desaparece bajo la lava en un instante. Su compañero intenta huir, pero con un movimiento fluido consigues agarrarle de la túnica y lanzarle a su perdición. Con un gesto enfadado te quitas el anillo y lo lanzas al mismo sitio, saludas a Påtår y continúas con tu aventura.\n","c2","g"],
["\n2 - 'No, si el anillo ya lo tengo, vengo a devolverlo'","Los minions se miran, confundidos, y te miran expectantes.\n\n- 'Ah. Perdona, estábamos sustituyendo a los anteriores protectores del anillo, no nos habían dicho que ya lo habían cogido. ¿Puedes... Uh... Puedes echarlo a la lava por favor?'\n\nMirando a los minions más detenidamente, ver que ambos están sudando abundantemente. Estás segura de que no es por el calor.\n\n- 'Claro, aquí va'\n\nTe quitas el Anillo de Poder del dedo, se lo muestras brevemente a los minions y lo arrojas al volcán. Tras un breve agradecimiento ambos suspiran aliviados y vuelven a su rincón. Tras saludar a Påtår continúas con tu aventura.","c2","g"],
["\n3 - ¿Eh Påtår, son amigos tuyos?","end","d"]]

i=["- 'Mira fulano, estoy hasta el gorro de vosotros. He despachado a Tjena, buscaos otro hobby. A mí me dejas pasar o lo que no va a tener ni pies ni cabeza vas a ser tú dentro de poco'\n\nLa figura encapuchada se queda inmóvil, pensando su próximo movimiento.\n\n- 'Vale. Voy ah... Uh... Voy a comprobar lo de Tjena, espera aquí. Luego si eso vuelvo en un rato'.\n\nEsperas un rato por curiosidad, pero está claro que el minion no tiene intención de volver.",
["\n\n1 - Continuar tu camino","","c2","h"]]

j=["- 'Mira, no sé quién eres, pero me he tirado meses matando a minions encapuchados para acabar con Tjena. Ya está muerto, ya no tienes maestro. Déjame en paz de una vez'\n- '¿Le has matado?'\n- 'Eso es lo que he dicho, sí. He ido al templo de hielo en la cima del sitio este...'\n- '¿Trofast?'\n- 'Sí, gracias. He estado ahí, he estado en la cueva de hielo, he invocado a Bjärnum, y Tjena ha muerto. Estoy volviendo a casa ya, vosotros me dais igual. ¿Me dejas pasar? Si quieres luchamos pero vamos, acabarás como los otros cientos'\n- '¿En la cueva de hielo? Espero que no le hayas puesto un dedo encima a Stjärnbräcka. De lo contrario...'\n- '¿A quién?'\n- 'El del organillo. Es mi... Uh... Me cae bien. Ya sabes'\n- 'Ah, sí, tenía pinta de majo. No le he hecho nada'\n- 'Pues hala, marcha a casa. Ya me buscaré otro trabajo'.\n\nLa figura encapuchada desaparece entre los matorrales en un abrir y cerrar de ojos, y te quedas sola en el bosque.",
["\n\n1 - Continuar con tu camino","","c2","h"]]

k=["Estás fuera del templo a Bjärnum. Una cosa menos para hacer. Echarás de menos su compañía, pero siempre puedes volver. Tal vez dediques parte de tu recién ganado tiempo libre para mantener el templo en order. Mira al camino frente a ti. Decides...",
["\n\n1 - Volver a subir al volcán Lerhyttan para deshacerte del Anillo de Poder","Decides escalar Lerhyttan de nuevo. Avanzas por el camino, pensando en todas aquellas escaleras.","c2","b"],
["\n2 - Adentrarse en Skarsta para olvidar el poder prohibido","","c2","d"],
["\n3 - Volver a casa. Ya lo has hecho todo.","","c3","a"]]

l=["- '¿Hay alguien?', insistes. Tras un momento un poco tenso, oyes algunas risas de fondo.\n- Aquí estamos, aventurera. Todos los dioses del partenón te felicitamos por tu hazaña. El poder ha sido devuelto, la deuda saldada. Marcha en paz.\n\nLa luz desaparece.",
["\n\n1 - Continuar con tu aventura","","c2","k"]]

m=["Alefjäll gruñe y murmura un poco, y se despierta en su sitio. Te lanza una mirada confusa mientras se quita las legañas. Te preguntaría a ver qué narices haces ahí, pero ya sabes que no es una persona de muchas palabras. Le explicas brevemente que Tjena ya no existe en este mundo y que necesitas olvidar Eneryda para que el futuro del reino no corra riesgo. Tras un buen rato tratando de despertarse, te señala a un altar de piedra en una esquina de la estancia y empieza a rebuscar en un cajón.",
["\n\n1 - Sentarse en el altar","","c2","o"],
["\n2 - Quedarse mirando","","c2","p"]]

n=["Alefjäll se sobresalta en su sitio y te mira enfurruñado. No hace falta que diga nada, ya sabes que le has fastidiado una buena siesta y que si Tjena estaba muerto podrías haber esperado un par de horas para despertarle. O un par de días. Le explias que ya no necesitas conocer Eneryda para salvar al reino y que es mejor para todos que lo olvides para siempre. Te asiente mientras se frota las sienes y te señala a un altar de piedra en uno de los rincones de la estancia mientras empieza a rebuscar en un cajón.",
["\n\n1 - Sentarse en el altar","","c2","o"],
["\n2 - Quedarse mirando","Te quedas mirando a Alefjäll como un pasmarote. Ya sabes exactamente lo que quiere, pero te gusta tocarle las narices. Finalmente encuentra algo en un cajón y se levanta de su asiento, empujándote hacia el altar.","c2","o"]]

o=["Te sientas en el altar, y Alefjäll se acerca a ti con lo que fuera que estuviera buscando en la mano, haciéndote gestos para que te tumbes. Lo que sea, si Tjena no ha podido acabar contigo, no va a pasar nada por dejar hacer a un señor mayor con un palo.\n\nSigues sus instrucciones y cierras los ojos, preparado para algún tipo de magia amnésica o ritual arcano. Lo único que sientes es un palo bastante gordo sacudiéndote en la cabeza. ",
["\n\n1 - ¡Ouch!","Antes de que puedas preguntarle qué narices está haciendo, Alefjäll vuelve a sacudirte con el palo. Tienes que reconocer que para ser un anciano tiene una fuerza extraordinaria. Tal vez más tarde, una vez recuperes el conocimiento. Ahora mismo estás completamente KO y no puedes hacer gran cosa.","c2","p"]]

p=["Una vez más te encuentras a las afueras de Skarsta. No sabes exactamente cómo has llegado ahí, pero te lo puedes imaginar. Te llevas la mano a la cabeza, intentando ver cómo de serio es el chichón. No ves al guarda ni a ningún otro ser vivo a tu alrededeor, y las puertas del complejo están cerradas. El chichón es considerable. Habías venido para olvidar algo, pero no recuerdas qué. ¡Otro trabajo bien hecho!\n\nTe incorporas con dificultad. Y ahora... ¿Qué?",
["\n\n1 - Volver a subir al volcán Lerhyttan para deshacerte del Anillo de Poder","Decides escalar Lerhyttan de nuevo. Avanzas por el camino, pensando en todas aquellas escaleras.","c2","b"],
["\n2 - Viajar al altar de Grönlid","La bendición de bjärnum debe de ser devuelta. Decides viajar al altar de Grönlid\n","c2","c"],
["\n3 - Ya está todo hecho: volver a casa","","c3","a"]]

