# -*- coding: utf-8 -*-
a=["'Un trabajo bien hecho'\n[ACTO III]\n\nNunca imaginaste que llegaría este día. Bueno, en realidad sí, has estado esperando este momento durante meses. Das tu primer paso en tu Släkt natal, admirando las vistas y oliendo el pan recién hecho y la hierba cortada. El poblado no ha cambiado mucho. Notas como una de las casas ha cambiado de color, y uno de los campos tiene más cosecha de lo habitual, pero todo sigue en su sitio. El anciano de la aldea te mira con cierta preocupación. Has vuelto tras erradicar el mal del reino, o has vuelto antes y la aldea va a acabar ardiendo para dar ambientación a la aventura. \n\nSus dudas se disuelven tras ver tu sonrisa, y te levanta una mano como saludo. Se lo devuelves entusiasmada.",
["\n\n1 - 'Saludos, venerable Bekväm! ¡Tjena ya no existe en este reino!'","La expresión del anciano se transforma de preocupación a alivio, y ves aparecer una sonrisa de oreja a oreja en su cara\n","c3","c"],
["\n2 - 'Bueno, pues ya está'","Haces un comentario casual sobre el éxito de tu misión. El anciano te mira extrañado. Tal vez estaba esperando algo más de teatrillo, pero comprende tu cansancio\n","c3","c"],
["\n3 - Levantar un pulgar","Haces un gesto con tu mano indicando el éxito de tu misión mientras sonríes. Te apetece más tirarte bajo un árbol que ponerte a hablar. Bekväm asiente.\n","c3","c"]]

b=["Te olvidas de devolver las cosas, porque total, ya habrá tiempo después. Corres al centro de la aldea. Parece desierta. Sólo hay una señora mayor que no reconoces barriendo el exterior de su casa.",
["\n\n1 - 'Hola, ¿Dónde está todo el mundo?'","Le diriges la palabra a la señora, que te mira sorprendida. \n\n- 'Estan todos con los preparativos para tu regreso. Esperábamos que devolver tus nuevos poderes te llevaría unos días más'\n- 'Ah, aún no los he devuelto. Quería pasarme por aquí primero'\n\nLa anciana te mira incrédula y furiosa.\n\n- '¡Cómo que aún no los has devuelto! ¡Pero qué irresponsabilidad es esa! ¡Es un paso importantísimo, no puedes ir por ahí con todo ese poder sin un objetivo en el que usarlos! ¡Es TODO UN ACTO de tu vida que te acabas de saltar, así por las buenas! Vuelve por donde has venido, te esperaremos con los brazos abiertos cuando hagas lo que tienes que hacer. La anciana te saca a empujones de la aldea y vuelve a su casa a barrer. Tienes que admitir que algo de razón tiene. \n", "c3", "d"]]

c=["Te sientas al lado del anciano a descanasar, por fin. La conversación pierde su carácter grave rápidamente, y te encuentras hablando del futuro con él.\n\n- 'Cuéntame aventurera. Bueno, heroina más bien. ¿Has devuelto todos los poderes?'\n-'Sí, por supuesto'\n- '¿Segura?'",
["\n\n1 - Completamente","'Por supuesto', le respondes. 'No dejaría algo así sin hacer. Si estoy aquí es porque mi aventura ha acabado'. El anciano te mira un rato, satisfecho.", "end", "f"],
["\n2 - Completamente (Mentira)","'Por supuesto', le respondes. 'No dejaría algo así sin hacer. Si estoy aquí es porque mi aventura ha acabado'. Evidentemente, todo esto es mentira. Te has dejado alguna cosa sin hacer. Pero qué más da.", "end", "g"],
["\n3 - La verdad es que no. Lo mismo me he dejado algo","- 'Tu vuelta ha sido prematura, entonces. Prematura, arriesgada e irresponsable. Has dejado que tus ansias por volver nublen tu juicio. Vuelve por donde has venido, seguiremos esperándote hasta que to obra haya acabado.'\n\nAsientes, algo avergonzada, y abandonas tu aldea una vez más.", "c3", "d"]]

d=["Te encuentras en el extremo de tu aldea. Hay algo que te has dejado sin hacer. No recuerdas exactamente qué es.",
["\n\n1 - Devolver el anillo a Lerhyttan","Decides volver a Lerhyttan para deshacerte del anillo.","c2","b"],
["\n2 - Viajar al altar de Grönlid","La bendición de bjärnum debe de ser devuelta. Decides viajar al altar de Grönlid\n","c2","c"],
["\n3 - Tratar de olvidar tu poder en Skarsta","Tenías que olvidarte de Eneryda. Y se te había olvidado. Lástima que dos errores no se cancelen tan fácilmente.\n","c2","d"],
["\n4 - Volver a la aldea","","c3","a"]]
