# -*- coding: utf-8 -*-
a=["Es el fin. No te preocupa, el fin tenía que llegar en algún momento. Tal vez lo peor sea que abandonaste este mundo sin saber si fuiste capaz de salvarlo.\n\nFIN"]

b=["- 'Anda, muérete'.\n\nEs lo último que oyes. Sí, has muerto. Sí, podía hacer eso. 'Palabra de poder', míralo en el manual. No, no puedes hacer nada. No haber cabreado al jefe final. No me mires así, yo sólo estoy narrando la historia. Vuelve a intentarlo si eso.\n\nFIN"]

c=["Bajas tu espada y dejas que el minion continúe hablando. Bla bla bla poderes de tal, bla bla bla amuleto de cual. Ya tienes esa información. Le insistes un poco para ver si le queda algo de diálogo que no hayas escuchado. Bla bla bla Reencarnación del mal, bla bla bla no olvides guardar antes de salir... Definitivamente se ha quedado sin cosas nuevas que decir. \n\nEn el momento en el que levantas tu espada para despacharle, notas un golpe en la espalda. Mirando hacia abajo ves la punta de una flecha saliendo de tu pecho antes de perder el conocimiento. Qué manera más tonta de morir, ¿Quién te mandaría darle cuerda?\n\nFIN"]

d=["Sin tomarte a los minions demasiado en serio, haces un comentario gracioso a Påtår. Antes de que puedas reaccionar, uno de ellos te lanza una piedra que te hace perder el equilibrio. Has subido miles de escalones para llegar ahí, y ahora estás cayendo por otros tantos miles. Mira que te avisaron. Te avisaron de las escaleras. Continúas cayendo hasta perder el conocimiento. Al menos has muerto con el trabajo hecho.\n\nFIN"]

e=["Te acercas sigilosamente a Alefjäll, y sin previo aviso das un golpe sobre la mesa que levanta el polvo de los libros y lo reparte por la estancia.\n\n- '¡Alefjäll!, exclamas.\n\nEste se despierta sobresaltado, saltando en su sitio, y mira frenéticamente a ambos lados.\n\n- '¡Ablwar ehblwa eh nrida!\n\nAlefjäll descarga toda su magia del susto, invocando sin pensarlo el mismo hechizo prohibido que estabas intentando olvidar. La estancia estalla en una bola de luz, y lo último que ves es todo lo que te rodea desintegrándose frente a ti. \n\nEstás muerta, pero supones que las risas han merecido la pena.\n\nFIN'"]

f=["La conversación continúa durante horas. Diferentes aldeanos se acercan a escuchar tus historias. Improvisáis una hoguera, y por primera vez en mucho tiempo, puedes relajarte sabiendo que el trabajo está hecho, y que aquellos que pasarán tus historias a futuras generaciones no volverán a conocer la maldición de Tjena. Miras a las estrellas, pensando en el futuro y agradeciendo tu buena fortuna\n\nFIN"]

g=["La conversación continúa durante horas. Ignoras gran parte de ella, pensando en qué pasará con las cosas que te has dejado por hacer. Tal vez un poco de esfuerzo extra habría asegurado tu tranquilidad. Tendrás que vivir con la duda... \n\nFIN"]